name: Build Relaxin TIPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      - name: Install tools
        run: |
          brew install ldid zstd

      - name: Build TIPA
        run: |
          make tipa

      - name: Upload TIPA
        uses: actions/upload-artifact@v4
        with:
          name: Relaxin-TIPA
          path: build/Artifacts/*.tipa
