name: Build Relaxin TIPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4


    - name: Install build tools
      run: |
        brew update

        brew install ldid dpkg ripgrep

        echo "Checking installed tools..."

        which ldid
        which dpkg-deb
        which rg


        echo "Installing trustcache..."

        curl -L https://github.com/opa334/trollstore-tools/releases/latest/download/trustcache \
        -o trustcache || true


        if [ -f trustcache ]; then
          chmod +x trustcache
          sudo mv trustcache /usr/local/bin/trustcache
        fi


        echo "Verify tools..."

        ldid -h || true
        dpkg-deb --version
        trustcache --help || true


    - name: Fix permissions
      run: |
        chmod +x DevKit/Helpers/*.sh


    - name: Build TIPA
      run: |
        make tipa


    - name: Find TIPA
      run: |
        find . -name "*.tipa"


    - name: Upload TIPA
      uses: actions/upload-artifact@v4
      with:
        name: Relaxin-tipa
        path: |
          **/*.tipa

    - name: Build TIPA
      run: |
        make tipa


    - name: Find TIPA
      run: |
        find . -name "*.tipa"


    - name: Upload TIPA
      uses: actions/upload-artifact@v4
      with:
        name: Relaxin-tipa
        path: "**/*.tipa"
