name: Build Relaxin TIPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build TIPA
        run: |
          chmod +x package-tipa.sh
          make tipa

      - name: Upload TIPA
        uses: actions/upload-artifact@v4
        with:
          name: Relaxin-TIPA
          path: build/Artifacts/*.tipa